### ISSUE TITLE
new architecture 0.3x

### ISSUE THREAD

**Issue by nphias** [Shadowstep33/Angular2Pixi#18] opened 2018-04-20 15:43 UTC
"Important! +v0.3.x comes with breaking changes including the removal of SceneComponent and RendererComponent to simplify the process. The docs will be updated accordingly"

please explain the new architecture... the current codebase still uses SceneComponent and RendererComponent

**Comment by Shadowstep33** [comment] 2018-04-22 20:47
Hi @nphias , I'll double check the the codebase - I may have left them in there for slight backwards compatibility or maybe I didn't publish the updates correctly. 

I will attempt to update the docs today, but in short I realized that SceneComponent and RendererComponent had two main shortcomings:

- AoT was failing because of the reliance of extensible components. Ideally, your custom components should no longer extend these components and the components provided with A2P should be more customizable and flexible out of the box and provide general abstract design patterns for how to craft your own
- Renderer and Scene were adding an extra layer of complexity that was not needed. The PixiService should create and keep track of the renderer and Scenes are really just loose collections of Sprites and Layers which should be offloaded to both a SceneService (I'm using it as a singleton factory) and however the app developer decides to organize their "scenes" (so the developer is less constrained).

**Comment by Shadowstep33** [comment] 2018-04-24 04:50
I have made some modifications to the wiki @nphias regarding the changes in v0.3 but there is still more to do. v0.4.1 has been published which should include the changes previously mentioned. Let me know if you have any issues or questions; I know this isn't exactly the cleanest library but this is essentially a passion project for me and is mainly getting updated as requests are made or as needed for the game I am currently using it for. Thanks for helping to test a2p and remaining patient :)

I will continue to update the docs this week and do some cleanup of the library over the coming weeks (there are some obsolete member variables and the like that are no longer needed and that can be removed towards the goal of simplification).

**Comment by nphias** [comment] 2018-04-24 21:27
Thanks Shadowstep .. yes it seems a lot better without the scene and render component.. i was thinking of a usecase where you might want multiple pixi renderers.. maybe that would be possible by creating new instances of the pixi service.. ..  I will try out 0.4x and give more feedback

**Comment by Shadowstep33** [comment] 2018-04-24 21:35
Ah yes, so you technically COULD inject PixiService into different
components to get a new instance and call init from there, though I
remember it not being advised by Ivan Popyleyshev, one of the main Pixi.js
bad asses. If PixiService had decent cleanup that destroys the renderer on
ngDestroy of the component, I think it would be okay as if I remember
correctly the problem is having multiple renderers simultaneously going.

Sounds like a decent improvement if you can supply some use cases where
youd need/want multiple renderers :)

**Comment by Shadowstep33** [comment] 2018-04-25 03:40
I am going to close this for now @nphias 

@gerkindev I would suggest peeping this thread in case it sheds any light on the changes

**Closed by Shadowstep33** 2018-04-25 03:40 UTC
